export const DummyMachine = [
  {
    id: 1,
    modelName: 'Axial-flow 3000',
    brandName: 'Case IH',
    conception: 'Cylindre Axial',
    engineKwPower: 210,
    engineCcPower: 180,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 500,
    TankLitre: 600,
    WeightKg: 6000,
    WorkingWidth: 14,
    CopiesNumber: 2,
  },
  {
    id: 2,
    modelName: 'Axial-flow 6000',
    brandName: 'Case IH',
    conception: 'Cylindre Axial',
    engineKwPower: 210,
    engineCcPower: 180,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 500,
    TankLitre: 600,
    WeightKg: 6000,
    WorkingWidth: 14,
    CopiesNumber: 2,
  },
  {
    id: 3,
    modelName: 'Axial-flow 8000',
    brandName: 'Case IH',
    conception: 'Cylindre Axial',
    engineKwPower: 210,
    engineCcPower: 180,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 500,
    TankLitre: 600,
    WeightKg: 6000,
    WorkingWidth: 14,
    CopiesNumber: 2,
  },
  {
    id: 4,
    modelName: 'Axial-flow 3000',
    brandName: 'Case IH',
    conception: 'Cylindre Axial',
    engineKwPower: 210,
    engineCcPower: 180,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 500,
    TankLitre: 600,
    WeightKg: 6000,
    WorkingWidth: 14,
    CopiesNumber: 2,
  },
  {
    id: 5,
    modelName: 'Axial-flow 6000',
    brandName: 'Case IH',
    conception: 'Cylindre Axial',
    engineKwPower: 210,
    engineCcPower: 180,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 500,
    TankLitre: 600,
    WeightKg: 6000,
    WorkingWidth: 14,
    CopiesNumber: 2,
  },
  {
    id: 6,
    modelName: 'Axial-flow 8000',
    brandName: 'Case IH',
    conception: 'Cylindre Axial',
    engineKwPower: 210,
    engineCcPower: 180,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 500,
    TankLitre: 600,
    WeightKg: 6000,
    WorkingWidth: 14,
    CopiesNumber: 2,
  },
  {
    id: 7,
    modelName: 'Axial-flow 3000',
    brandName: 'Case IH',
    conception: 'Cylindre Axial',
    engineKwPower: 210,
    engineCcPower: 180,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 500,
    TankLitre: 600,
    WeightKg: 6000,
    WorkingWidth: 14,
    CopiesNumber: 2,
  },
  {
    id: 8,
    modelName: 'Axial-flow 6000',
    brandName: 'Case IH',
    conception: 'Cylindre Axial',
    engineKwPower: 210,
    engineCcPower: 180,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 500,
    TankLitre: 600,
    WeightKg: 6000,
    WorkingWidth: 14,
    CopiesNumber: 2,
  },
  {
    id: 9,
    modelName: 'Axial-flow 8000',
    brandName: 'Case IH',
    conception: 'Cylindre Axial',
    engineKwPower: 210,
    engineCcPower: 180,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 500,
    TankLitre: 600,
    WeightKg: 6000,
    WorkingWidth: 14,
    CopiesNumber: 2,
  },
  {
    id: 10,
    modelName: 'Axial-flow 3000',
    brandName: 'Case IH',
    conception: 'Cylindre Axial',
    engineKwPower: 210,
    engineCcPower: 180,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 500,
    TankLitre: 600,
    WeightKg: 6000,
    WorkingWidth: 14,
    CopiesNumber: 2,
  },
  {
    id: 11,
    modelName: 'Axial-flow 6000',
    brandName: 'Case IH',
    conception: 'Cylindre Axial',
    engineKwPower: 210,
    engineCcPower: 180,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 500,
    TankLitre: 600,
    WeightKg: 6000,
    WorkingWidth: 14,
    CopiesNumber: 2,
  },
  {
    id: 12,
    modelName: 'Axial-flow 8000',
    brandName: 'Case IH',
    conception: 'Cylindre Axial',
    engineKwPower: 210,
    engineCcPower: 180,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 500,
    TankLitre: 600,
    WeightKg: 6000,
    WorkingWidth: 14,
    CopiesNumber: 2,
  },
  {
    id: 13,
    modelName: 'Axial-flow 3000',
    brandName: 'Case IH',
    conception: 'Cylindre Axial',
    engineKwPower: 210,
    engineCcPower: 180,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 500,
    TankLitre: 600,
    WeightKg: 6000,
    WorkingWidth: 14,
    CopiesNumber: 2,
  },
  {
    id: 14,
    modelName: 'Axial-flow 6000',
    brandName: 'Case IH',
    conception: 'Cylindre Axial',
    engineKwPower: 210,
    engineCcPower: 180,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 500,
    TankLitre: 600,
    WeightKg: 6000,
    WorkingWidth: 14,
    CopiesNumber: 2,
  },
  {
    id: 15,
    modelName: 'Axial-flow 8000',
    brandName: 'Case IH',
    conception: 'Cylindre Axial',
    engineKwPower: 210,
    engineCcPower: 180,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 500,
    TankLitre: 600,
    WeightKg: 6000,
    WorkingWidth: 14,
    CopiesNumber: 2,
  },
];
